### ISSUE TITLE
trbcite with page numbers

### ISSUE THREAD

**Issue by retorquere** [chiehrosswang/TRB_LaTeX_tex#11]
Is it possible to include page numbers when citing? `\trbcite[130]{citekey}` doesn't seem to work.

**Comment by chiehrosswang** [comment]
It is not a defined option as of now.  However, there is an easy work-around: providing page(s) in your .bib file.  For example, article Koppelman2005 in [the .bib file used in this template](https://github.com/chiehrosswang/TRB_LaTeX_tex/blob/master/trb_template.bib) has `pages = {63--69}` in its BibTeX entry.  In the Reference section (bibliography), this reference looks like below.  Note the pages are shown in the end.

> [5] Koppelman, F. S. and L. A. Garrow, Efficiently Estimating Nested Logit Models with Choice-
11 Based Samples: Example Applications. Transportation Research Record, Journal of the Trans12
portation Research Board, Vol. 1921, No. 1, 2005, pp. 63–69.

**Comment by retorquere** [comment]
But that would make it impossible to cite different page ranges in different places of my own article.

**Comment by gregmacfarlane** [comment]
Typically in-text page references are only used when referring to a direct quote. [From the APA style guide](http://guides.libraries.psu.edu/apaquickguide/intext): 

> APA in-text citation style uses the author's last name and the year of publication, for example: (Field, 2005). For direct quotations, include the page number as well, for example: (Field, 2005, p. 14).

TRB doesn't provide any information for citations with page references, but it doesn't seem that their  [guide for authors](http://onlinepubs.trb.org/onlinepubs/am/infoforauthors.pdf) addresses it at all:

> Denote a reference at the appropriate place in the text with an italicized Arabic numeral in
parentheses, e.g., (2). Do not denote text references with superscripts.

I myself have never seen a (*3*, p. 114) quote citation in TRR. I wish that TRB would simply adopt an accepted citation style (e.g. APA), but until they explicitly address this in some way I don't know that we need to revise the citation formatters.

**Comment by chiehrosswang** [comment]
I have never seen pages in in-line citations in TRR either.  I agree with you @gregmacfarlane that we don't need to revise the citation formatter unless more clear guidelines or style has been adopted.
