### ISSUE TITLE
reference format in the template is different with the official word

### ISSUE THREAD

**Issue by zwbai** [chiehrosswang/TRB_LaTeX_tex#15]
Hi!
Dose anyone knows why the reference format in the template is different with the official word？
Is that OK for submission?

**Comment by gregmacfarlane** [comment]
Can you be more specific? Show examples. In general they won't reject for minor issues.

**Comment by chiehrosswang** [comment]
Agree with @gregmacfarlane, @zwbai can you show some examples?  My experience as a reviewer is that TRB typically does not strictly enforce reference formatting.

**Comment by zwbai** [comment]
sorry for late reply.
here is a example for the reference format given by TRB offical
![tem_ref](https://user-images.githubusercontent.com/23632221/43561069-ea2a9f06-9647-11e8-8d7e-5fa660e71542.PNG)

here is the reference format that generated by the Latex
![trb_ref](https://user-images.githubusercontent.com/23632221/43561070-ea838f4e-9647-11e8-867d-0bc05afc45db.PNG)

**Comment by zwbai** [comment]
Oh, no ,I upload the shortcut reversed.

**Comment by zwbai** [comment]
sorry for late reply.
here is a example for the reference format given by TRB offical
![trb_ref](https://user-images.githubusercontent.com/23632221/43561192-76380786-9648-11e8-96d3-12b3c8e4d0ea.PNG)
here is the reference format that generated by the Latex
![tem_ref](https://user-images.githubusercontent.com/23632221/43561196-7ce4d136-9648-11e8-912c-4a4b6c77d34a.PNG)

Is there anyone meet the same situation?
How can I make the format same as the official template?

**Comment by zwbai** [comment]
![image](https://user-images.githubusercontent.com/23632221/43562231-e428d360-964d-11e8-8e24-62b807357c8a.png)

![image](https://user-images.githubusercontent.com/23632221/43562254-1071bf90-964e-11e8-8b02-6f89c6d3ae0b.png)

**Comment by chiehrosswang** [comment]
Add `\renewcommand\@biblabel[1]{#1.\hspace{0.25in}} ` to [trbunofficial.cls](https://github.com/chiehrosswang/TRB_LaTeX_tex/blob/master/trbunofficial.cls) and it does the trick.  I updated the Master repository and now the [trbunofficial.cls](https://github.com/chiehrosswang/TRB_LaTeX_tex/blob/master/trbunofficial.cls)  and [trb_template.pdf](https://github.com/chiehrosswang/TRB_LaTeX_tex/blob/master/trb_template.pdf) reflect the changes.

![image](https://user-images.githubusercontent.com/15328803/43563050-327186b2-95ee-11e8-9188-26edd067c5c9.png)

**Comment by zwbai** [comment]
WOW!!
Thanks a lot~
:D
