### ISSUE TITLE
Word count does not work in Overleaf

### ISSUE THREAD

**Issue by chiehrosswang** [chiehrosswang/TRB_LaTeX_tex#18]
Need to change the macro to make word count work in Overleaf

**Comment by hrgentry** [comment]
Awesome work.  I have used this template for a couple of years. 

`wordcount` broke locally as well, it seems to have a problem with `\@@localdummy`. Also, is it possible to rename `\trbcite` to `\citep` to keep the name more consistent?

**Comment by chiehrosswang** [comment]
@hrgentry thanks.  I was able to compile it successfully with correct `wordcount` in TeXstudio locally.  What OS and TeX environment are you using?  Also, I've replaced `\trbcite` with `\citep` in the master.

**Comment by hrgentry** [comment]
Thanks for the update. I am using macOS, tried to compile with the vanilla latex and latexmk but with no luck. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chiehrosswang** [comment]
Thanks for the response.  Unfortunately, I do not have access to macOS to test this.  I hope other users can help with this.

**Comment by JeroenSchmidt** [comment]
@chiehrosswang is there a temporary workaround to get overleaf to display the correct word count?

**Comment by chiehrosswang** [comment]
> @chiehrosswang is there a temporary workaround to get overleaf to display the correct word count?

I will work on this tonight and will let you know.

**Comment by chiehrosswang** [comment]
@JeroenSchmidt the current master works in Overleaf now.  Let me know if you have any other questions.

**Comment by CarlinLiao** [comment]
Thanks for the update!

I just wanted to comment that I was trying to figure out why the word count wasn't working on an Overleaf project I updated to match the master. It turns out it was because I'd renamed my main tex file differently from `trb_template.tex` which didn't play well with the `cls` file command. A small mistake on my part, but I thought it was worth mentioning.

**Comment by chiehrosswang** [comment]
Yes, thanks @CarlinLiao for the feedback.  I will add this constraint to Readme so that people are aware of this.
