### ISSUE TITLE
Complete overwrite of files

### ISSUE THREAD

**Issue by akstrfn** [chiehrosswang/TRB_LaTeX_tex#21]
Wanted to update my template to follow this repo and some conflicts emerged. I proceeded with git blame to see when and why some of the changes occured and saw the commits 85d4b9657f11ce3e9b7a731d4f122da84b2029c1 and 34612638be74ed919067c3dae61df57fab3ba690. Why overwrite?

**Comment by chiehrosswang** [comment]
Some dumb issue when I tried to sync the master on my local drive.  The files should be the same as before the overwrite though.

**Comment by akstrfn** [comment]
They were the same. I see the problem, git can be confusing sometimes 🙂

**Comment by chiehrosswang** [comment]
Good.  Glad I didn't break anything :)
