### ISSUE TITLE
Is it possible to get word count to include included sections?

### ISSUE THREAD

**Issue by slremy** [chiehrosswang/TRB_LaTeX_tex#8]
I don't know if this is an easy extension.. but is it possible to include text that is in `\input{someOther.tex}` in the word count?

**Comment by chiehrosswang** [comment]
Good question, I have not really explored possible options, will look into it.  Let me know if you come across with some solutions.

**Comment by slremy** [comment]
Defintely!

**Comment by chiehrosswang** [comment]
Closing this issue since it is unlikely that we need to combine separate .tex files into a file.
